/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['./demo/hello.js']) {
  _$jscoverage['./demo/hello.js'] = [];
  _$jscoverage['./demo/hello.js'][1] = 0;
  _$jscoverage['./demo/hello.js'][3] = 0;
  _$jscoverage['./demo/hello.js'][4] = 0;
  _$jscoverage['./demo/hello.js'][7] = 0;
  _$jscoverage['./demo/hello.js'][8] = 0;
  _$jscoverage['./demo/hello.js'][11] = 0;
  _$jscoverage['./demo/hello.js'][12] = 0;
}
_$jscoverage['./demo/hello.js'][1]++;
var HELLO = ["o", "l", "l", "e", "h"];
_$jscoverage['./demo/hello.js'][3]++;
export.hello = (function () {
  _$jscoverage['./demo/hello.js'][4]++;
  return HELLO.reverse().join("");
});
_$jscoverage['./demo/hello.js'][7]++;
export.help = (function () {
  _$jscoverage['./demo/hello.js'][8]++;
  return "@\u67d0mm:Tonight go party,I'm a sexy girl.I sometimes good sometimes bad\uff0cthis is me,you don't like me you can get out\uff01";
});
_$jscoverage['./demo/hello.js'][11]++;
export.translate = (function () {
  _$jscoverage['./demo/hello.js'][12]++;
  return "@\u70ed\u5fc3\u7f51\u53cb\u7ffb\u8bd1\uff1a\u5b50\u65f6\u8d8b\u515a\u90e8\uff0c\u59be\u672c\u662f\u6027\u5974\uff1b\u95f4\u6216\u6709\u826f\u8fd0\uff0c\u95f4\u6216\u827a\u7a0d\u758f\uff1b\u672c\u8272\u65b9\u662f\u6211\uff0c\u4efb\u541b\u6765\u53bb\u5982\u3002";
});
_$jscoverage['./demo/hello.js'].source = ["var HELLO = ['o','l','l','e','h'];","","export.hello = function(){","  return HELLO.reverse().join('');","};","","export.help = function(){","  return '@&#26576;mm:Tonight go party,I\\'m a sexy girl.I sometimes good sometimes bad&#65292;this is me,you don\\'t like me you can get out&#65281;';","};","","export.translate = function(){","  return '@&#28909;&#24515;&#32593;&#21451;&#32763;&#35793;&#65306;&#23376;&#26102;&#36235;&#20826;&#37096;&#65292;&#22974;&#26412;&#26159;&#24615;&#22900;&#65307;&#38388;&#25110;&#26377;&#33391;&#36816;&#65292;&#38388;&#25110;&#33402;&#31245;&#30095;&#65307;&#26412;&#33394;&#26041;&#26159;&#25105;&#65292;&#20219;&#21531;&#26469;&#21435;&#22914;&#12290;'","};"];
