/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['hello.js']) {
  _$jscoverage['hello.js'] = [];
  _$jscoverage['hello.js'][1] = 0;
  _$jscoverage['hello.js'][3] = 0;
  _$jscoverage['hello.js'][4] = 0;
  _$jscoverage['hello.js'][7] = 0;
  _$jscoverage['hello.js'][8] = 0;
  _$jscoverage['hello.js'][11] = 0;
  _$jscoverage['hello.js'][12] = 0;
}
_$jscoverage['hello.js'][1]++;
var HELLO = ["o", "l", "l", "e", "h"];
_$jscoverage['hello.js'][3]++;
export.hello = (function () {
  _$jscoverage['hello.js'][4]++;
  return HELLO.reverse().join("");
});
_$jscoverage['hello.js'][7]++;
export.help = (function () {
  _$jscoverage['hello.js'][8]++;
  return "@\u00e6\u009f\u0090mm:Tonight go party,I'm a sexy girl.I sometimes good sometimes bad\u00ef\u00bc\u008cthis is me,you don't like me you can get out\u00ef\u00bc\u0081";
});
_$jscoverage['hello.js'][11]++;
export.translate = (function () {
  _$jscoverage['hello.js'][12]++;
  return "@\u00e7\u0083\u00ad\u00e5\u00bf\u0083\u00e7\u00bd\u0091\u00e5\u008f\u008b\u00e7\u00bf\u00bb\u00e8\u00af\u0091\u00ef\u00bc\u009a\u00e5\u00ad\u0090\u00e6\u0097\u00b6\u00e8\u00b6\u008b\u00e5\u0085\u009a\u00e9\u0083\u00a8\u00ef\u00bc\u008c\u00e5\u00a6\u00be\u00e6\u009c\u00ac\u00e6\u0098\u00af\u00e6\u0080\u00a7\u00e5\u00a5\u00b4\u00ef\u00bc\u009b\u00e9\u0097\u00b4\u00e6\u0088\u0096\u00e6\u009c\u0089\u00e8\u0089\u00af\u00e8\u00bf\u0090\u00ef\u00bc\u008c\u00e9\u0097\u00b4\u00e6\u0088\u0096\u00e8\u0089\u00ba\u00e7\u00a8\u008d\u00e7\u0096\u008f\u00ef\u00bc\u009b\u00e6\u009c\u00ac\u00e8\u0089\u00b2\u00e6\u0096\u00b9\u00e6\u0098\u00af\u00e6\u0088\u0091\u00ef\u00bc\u008c\u00e4\u00bb\u00bb\u00e5\u0090\u009b\u00e6\u009d\u00a5\u00e5\u008e\u00bb\u00e5\u00a6\u0082\u00e3\u0080\u0082";
});
_$jscoverage['hello.js'].source = ["var HELLO = ['o','l','l','e','h'];","","export.hello = function(){","  return HELLO.reverse().join('');","};","","export.help = function(){","  return '@&#230;&#159;&#144;mm:Tonight go party,I\\'m a sexy girl.I sometimes good sometimes bad&#239;&#188;&#140;this is me,you don\\'t like me you can get out&#239;&#188;&#129;';","};","","export.translate = function(){","  return '@&#231;&#131;&#173;&#229;&#191;&#131;&#231;&#189;&#145;&#229;&#143;&#139;&#231;&#191;&#187;&#232;&#175;&#145;&#239;&#188;&#154;&#229;&#173;&#144;&#230;&#151;&#182;&#232;&#182;&#139;&#229;&#133;&#154;&#233;&#131;&#168;&#239;&#188;&#140;&#229;&#166;&#190;&#230;&#156;&#172;&#230;&#152;&#175;&#230;&#128;&#167;&#229;&#165;&#180;&#239;&#188;&#155;&#233;&#151;&#180;&#230;&#136;&#150;&#230;&#156;&#137;&#232;&#137;&#175;&#232;&#191;&#144;&#239;&#188;&#140;&#233;&#151;&#180;&#230;&#136;&#150;&#232;&#137;&#186;&#231;&#168;&#141;&#231;&#150;&#143;&#239;&#188;&#155;&#230;&#156;&#172;&#232;&#137;&#178;&#230;&#150;&#185;&#230;&#152;&#175;&#230;&#136;&#145;&#239;&#188;&#140;&#228;&#187;&#187;&#229;&#144;&#155;&#230;&#157;&#165;&#229;&#142;&#187;&#229;&#166;&#130;&#227;&#128;&#130;'","};"];
